'use client';
import { useRef, useEffect, useState, useCallback } from 'react';

interface NotesViewerProps {
  html: string;
  isStreaming: boolean;
  title?: string;
  onStop?: () => void;
}

const PRINT_STYLES = `
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Inter', sans-serif; color: #111827; background: white; padding: 2rem; max-width: 900px; margin: 0 auto; line-height: 1.7; }
  h1 { font-size: 1.75rem; font-weight: 700; margin: 1.5rem 0 0.75rem; color: #111827; }
  h2 { font-size: 1.35rem; font-weight: 600; margin: 1.25rem 0 0.5rem; color: #1e3a8a; border-bottom: 2px solid #dbeafe; padding-bottom: 0.25rem; }
  h3 { font-size: 1.1rem; font-weight: 600; margin: 1rem 0 0.4rem; color: #1d4ed8; }
  p { margin: 0.5rem 0; }
  ul, ol { margin: 0.5rem 0; padding-left: 1.5rem; }
  li { margin: 0.25rem 0; }
  strong { font-weight: 600; }
  code { background: #f3f4f6; padding: 0.125rem 0.375rem; border-radius: 0.25rem; font-family: monospace; font-size: 0.875rem; }
  pre { background: #1f2937; color: #f9fafb; padding: 1rem; border-radius: 0.5rem; overflow-x: auto; margin: 0.75rem 0; }
  pre code { background: none; padding: 0; color: inherit; }
  table { width: 100%; border-collapse: collapse; margin: 0.75rem 0; }
  th { background: #1e3a8a; color: white; padding: 0.5rem 0.75rem; text-align: left; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  td { padding: 0.5rem 0.75rem; border-bottom: 1px solid #e5e7eb; }
  tr:nth-child(even) td { background: #f9fafb; }
  .question-card { border: 1px solid #e5e7eb; border-radius: 0.75rem; margin: 1.5rem 0; overflow: hidden; break-inside: avoid; page-break-inside: avoid; }
  .question-header { background: #1e3a8a; color: white; padding: 0.75rem 1rem; font-weight: 600; font-size: 1rem; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  .prescribed-answer { background: #eef3fc; border-left: 4px solid #1a5cb8; padding: 0.75rem 1rem; margin: 0.75rem 0; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  .mtech-answer { padding: 0.75rem 1rem; margin: 0.5rem 0; }
  .diagram-box { background: #f8f9fc; border: 1px solid #e5e7eb; padding: 0.75rem; margin: 0.75rem 0; text-align: center; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  .real-world { background: #edfbf4; border-left: 4px solid #0a7a45; padding: 0.75rem 1rem; margin: 0.75rem 0; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  .exam-tips { background: #fef3f0; border-left: 4px solid #a31515; padding: 0.75rem 1rem; margin: 0.75rem 0; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  .section-label { font-size: 0.75rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 0.35rem; }
  svg { max-width: 100%; height: auto; }
  @page { margin: 1.5cm; }
  @media print { .question-card { break-inside: avoid; } }
`;

/** Split HTML into individual question-card chunks */
function splitIntoCards(html: string): string[] {
  if (!html) return [];
  const parts = html.split(/(?=<div[^>]*class="[^"]*question-card[^"]*")/i);
  return parts.filter(p => p.trim().length > 0);
}

/** Extract the header text from a card chunk for display */
function extractCardLabel(cardHtml: string, index: number): string {
  const match = cardHtml.match(/<div[^>]*class="[^"]*question-header[^"]*"[^>]*>([\s\S]*?)<\/div>/i);
  if (match) {
    const text = match[1].replace(/<[^>]+>/g, '').trim();
    return text.slice(0, 60) + (text.length > 60 ? '…' : '');
  }
  return `Question ${index + 1}`;
}

function openPrintWindow(title: string, bodyHtml: string) {
  const w = window.open('', '_blank');
  if (!w) return;
  w.document.write(`<!DOCTYPE html><html><head>
    <title>${title}</title>
    <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>${PRINT_STYLES}</style>
  </head><body>
    <h1 style="color:#1e3a8a;border-bottom:3px solid #1e3a8a;padding-bottom:.5rem;margin-bottom:1.5rem;">
      📚 ${title}
    </h1>
    ${bodyHtml}
    <div style="margin-top:3rem;padding-top:1rem;border-top:1px solid #e5e7eb;text-align:center;color:#9ca3af;font-size:.75rem;">
      Generated by ExamNote AI — ${new Date().toLocaleDateString()}
    </div>
  </body></html>`);
  w.document.close();
  setTimeout(() => w.print(), 500);
}

export default function NotesViewer({ html, isStreaming, title, onStop }: NotesViewerProps) {
  const viewerRef = useRef<HTMLDivElement>(null);
  const [showPartialExport, setShowPartialExport] = useState(false);
  const [exportUpTo, setExportUpTo] = useState<number | null>(null);

  // Auto-scroll during streaming
  useEffect(() => {
    if (isStreaming && viewerRef.current) {
      viewerRef.current.scrollTop = viewerRef.current.scrollHeight;
    }
  }, [html, isStreaming]);

  // Close partial export panel when streaming starts
  useEffect(() => {
    if (isStreaming) setShowPartialExport(false);
  }, [isStreaming]);

  const cards = splitIntoCards(html);
  const cardCount = cards.length;

  const handleFullExport = useCallback(() => {
    openPrintWindow(title || 'ExamNote AI — Study Notes', html);
  }, [html, title]);

  const handlePartialExport = useCallback((upTo: number) => {
    const subset = cards.slice(0, upTo).join('');
    const label = upTo === 1 ? 'Q1 only' : `Q1–Q${upTo}`;
    openPrintWindow(`${title || 'ExamNote AI'} (${label})`, subset);
    setShowPartialExport(false);
  }, [cards, title]);

  if (!html) return null;

  return (
    <div className="flex flex-col h-full">
      {/* ── Toolbar ── */}
      <div className="flex items-center justify-between px-4 py-2.5 bg-gray-50 border-b border-gray-200 no-print flex-wrap gap-2">
        <div className="flex items-center gap-2">
          <span className="text-sm font-medium text-gray-700">📋 Generated Notes</span>
          {isStreaming && (
            <span className="flex items-center gap-1.5 text-xs text-blue-600 bg-blue-50 px-2 py-0.5 rounded-full">
              <span className="w-1.5 h-1.5 bg-blue-500 rounded-full animate-pulse" />
              Generating…
            </span>
          )}
          {!isStreaming && cardCount > 0 && (
            <span className="text-xs text-gray-400 bg-gray-100 px-2 py-0.5 rounded-full">
              {cardCount} question{cardCount !== 1 ? 's' : ''}
            </span>
          )}
        </div>

        <div className="flex items-center gap-2">
          {/* ── STOP button — visible while streaming ── */}
          {isStreaming && onStop && (
            <button
              onClick={onStop}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-red-600 text-white text-xs font-semibold rounded-lg hover:bg-red-700 transition-colors shadow-sm animate-pulse"
            >
              ⏹ Stop &amp; Export Now
            </button>
          )}

          {/* ── Export buttons — visible when not streaming ── */}
          {!isStreaming && (
            <>
              {/* Partial export toggle */}
              {cardCount > 1 && (
                <div className="relative">
                  <button
                    onClick={() => setShowPartialExport(v => !v)}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-amber-500 text-white text-xs font-medium rounded-lg hover:bg-amber-600 transition-colors"
                    title="Export only specific questions"
                  >
                    ✂️ Partial Export
                  </button>

                  {showPartialExport && (
                    <div className="absolute right-0 top-9 z-50 bg-white border border-gray-200 rounded-xl shadow-xl p-3 w-72">
                      <p className="text-xs font-semibold text-gray-600 mb-2 uppercase tracking-wide">
                        Export up to which question?
                      </p>
                      <div className="max-h-56 overflow-y-auto space-y-1">
                        {cards.map((card, i) => (
                          <button
                            key={i}
                            onClick={() => handlePartialExport(i + 1)}
                            className="w-full text-left px-3 py-2 text-xs rounded-lg hover:bg-blue-50 hover:text-blue-700 transition-colors group flex items-start gap-2"
                          >
                            <span className="flex-shrink-0 w-5 h-5 bg-blue-100 text-blue-700 rounded-full flex items-center justify-center font-bold text-[10px] mt-0.5">
                              {i + 1}
                            </span>
                            <span className="text-gray-700 group-hover:text-blue-700 line-clamp-2">
                              {extractCardLabel(card, i)}
                            </span>
                          </button>
                        ))}
                      </div>
                      <button
                        onClick={() => setShowPartialExport(false)}
                        className="mt-2 w-full text-center text-xs text-gray-400 hover:text-gray-600"
                      >
                        Cancel
                      </button>
                    </div>
                  )}
                </div>
              )}

              {/* Full export */}
              <button
                onClick={handleFullExport}
                className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 text-white text-xs font-medium rounded-lg hover:bg-blue-700 transition-colors"
              >
                🖨️ Export PDF
              </button>
            </>
          )}
        </div>
      </div>

      {/* ── Notes content ── */}
      <div
        ref={viewerRef}
        className="flex-1 overflow-y-auto p-5"
        style={{ maxHeight: 'calc(100vh - 200px)' }}
      >
        <div
          className={`notes-content ${isStreaming ? 'streaming-cursor' : ''}`}
          dangerouslySetInnerHTML={{ __html: html }}
        />
      </div>

      {/* ── Floating STOP pill — anchored bottom-right during streaming ── */}
      {isStreaming && onStop && (
        <div className="sticky bottom-4 flex justify-end px-4 no-print pointer-events-none">
          <button
            onClick={onStop}
            className="pointer-events-auto flex items-center gap-2 px-4 py-2.5 bg-red-600 text-white text-sm font-semibold rounded-full shadow-2xl hover:bg-red-700 transition-all border-2 border-white"
          >
            <span className="w-2 h-2 bg-white rounded-sm" />
            Stop — Export what's ready
          </button>
        </div>
      )}
    </div>
  );
}
